### PR TITLE
fix np.warnings to use the warnings library directly instead

### LINKED ISSUE #130: module 'numpy' has no attribute 'warnings' AttributeError with numpy > 1.23.x
Bug:
Given I have installed numpy 1.24 and sweetviz 2.1.4 (the latest)
When I call any sweetviz function which instantiates a GraphNumeric class
The code throws: `AttributeError: module 'numpy' has no attribute 'warnings' 

Expected:
Either sweetviz pins numpy to <1.24 where np.warnings existed
Or ideally,
graph_numeric is made to work with the latest numpy

Here is a log of the error on mac (monterey with m1 chip) and python3.10. The graph numeric class calls np.warnings (https://github.com/fbdesignpro/sweetviz/blob/master/sweetviz/graph_numeric.py), which works for 1.23.x, but was removed in 1.24. I cannot find the removal in the numpy release notes, but it definitely seems to have been removed.

Screenshot 2023-01-05 at 10 30 21

### PR DESCRIPTION
**Pull request by frank1010111**
Fixes #130 by using `warnings` directly rather than through numpy.

A quick test script:
```
import pandas as pd
import sweetviz as sv
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
report = sv.analyze(iris)
```

### CODE REVIEW

**Comment by Stephaniav1901** [comment]
Still not working! 

I tried:

import pandas as pd
import sweetviz as sv
import numpy as np
import warnings
import tqdm as notebook_tqdm

Still get same error.

**Comment by frank1010111** [comment]
How did you install sweetviz?
When I clone the repository, install it using pip locally, and then run the sample script, it fixes the issue. An easier way to pip install my fix might be
```
pip install git+https://github.com/frank1010111/sweetviz.git@d6f4d8bb98ffddc2123bec57b080ba86fc64c6f8
```

**Comment by Stephaniav1901** [comment]
Awesome!! It worked! Thank you.

**Comment by rogargon** [comment]
Confirmed, it works when installing sweetviz from @frank1010111 fork. Otherwise, I'm getting an error and unable to generate the report

**Comment by jwergieluk** [comment]
Just came here to contribute the same fix. Can also confirm that this solves the warnings problem occurring with numpy 1.24.3

**Comment by shivamsp133** [comment]
Did not work for me.

**Comment by pawel-jasnowski** [comment]
It works well that way in Jupyter 👍 th

import numpy as np
import sweetviz as sv
import pandas as pd
import warnings
!pip install git+https://github.com/frank1010111/sweetviz.git@d6f4d8bb98ffddc2123bec57b080ba86fc64c6f8

**Comment by vgrabovets** [comment]
@fbdesignpro Maybe it's time to merge it and release new version?

**Pull request merged**
