### PR TITLE
Replace `.iteritems()` → `.items()` (Fix  #141)

### LINKED ISSUE #141: AttributeError: 'DataFrame' object has no attribute 'iteritems'
I am using Python 3.11.2, i get this error just by trying to load the dataframe to sweetviz analyze. 

`financial_df = pd.read_excel('2023-04-05.xlsx')`
`my_report = sv.analyze(financial_df)`

### PR DESCRIPTION
**Pull request by GegznaV**
- Closes  #141

Also related to

-  #128

### CODE REVIEW

**Comment by MrMimic** [comment]
+1 :rocket:

**Comment by seanbearden** [comment]
+1 🚀

**Comment by pepaczz** [comment]
Hi, it would be great to have this commit merged. Downgrading pandas to make the things working starts to be a no-go solution. Thanks a lot.

**Comment by fbdesignpro** [comment]
Will do, thank you!

**Comment by MrMimic** [comment]
> Will do, thank you!

DO you plan to release a new version containing this hotfix @fbdesignpro ? :pray:

**Comment by nicolocarissimi** [comment]
🚀

**Comment by Sagners** [comment]
I can't wait for your new release

**Pull request merged**
