### PR TITLE
Update dataframe_page.html

### PR DESCRIPTION
**Pull request by a246530**
Added meta charset UTF-8 into head

### CODE REVIEW

**Comment by fbdesignpro** [comment]
Hi @a246530! I'm not sure if you got notified of my post on the closed pull request #32, but thanks so much for your contribution and for submitting this as a standalone fix as it looks good but as you probably surmised, #32 had all those other changes which will be nice to treat separately. :)

**Comment by fbdesignpro** [comment]
@a246530 haha I think our messages crossed ;) this looks safe enough I will merge right now. It's also my first open source project so I totally understand. :) Thanks again!

**Comment by a246530** [comment]
Yea haha I just commented on the closed one explaining why/how it happened. I am a noob.

**Comment by fbdesignpro** [comment]
@a246530 I'm assuming you had a similar character problem and this fixed it? I just want to make sure there IS a before/after confirmed fix test case somewhere :)

**Comment by a246530** [comment]
There is not. I was going to ask about that dataset in French that had an issue. All my char sets have been supported without it. You can hold up until I test. Hoping to do that today

**Comment by fbdesignpro** [comment]
@a246530 Thank you!! I still won't have much time to look into these in the coming days so that will be great! keep me posted. I will be doing similar tests for #22 before merging and publishing a whole new version to pip etc. ASAP. Why can't days have 30 hours? :P

**Comment by a246530** [comment]
Well if you were looking at it from perspective of a person and they were flying back through timezones.....haha

I will update this once I test. I also have a dataset that had errors that #22 should fix. Will test and comment.

**Comment by fbdesignpro** [comment]
@a246530 I tried it on my end and it does work, however I am getting "missing glyphs" warnings (i.e. missing CJK symbols will not show up correctly in graphs, but at least they will show up correctly in text).

I will work on fixing CJK in graphs when I have time soon-ish, but in the meantime I just wanted to confirm this is the behavior you're seeing also (i.e. warnings during report generation, BUT at least successful rendering for text but not graphs)

**Pull request merged**
